[package]
name = "git-overlapping"
version = "0.1.0"
edition = "2021"

[dependencies.futures-io]
git = "https://github.com/rust-lang/futures-rs"

[dependencies.futures-sink]
git = "https://github.com/rust-lang/futures-rs"
default-features = false
