[package]
name = "baz"
version = "0.1.0"
edition = "2021"

[dependencies]
foo = { path = "../foo" }
bar = { path = "../bar" }

# https://github.com/ipetkov/crane/issues/802
[dependencies.crane-test-repo]
package = "hello"
git = "https://github.com/ipetkov/crane-test-repo"
branch = "excludes"
