cargo-features = ["some unstable features"]
[[bench]]
edition = "2015"
name = "bench1"
path = "src/bench1.rs"

[[bench]]
edition = "2018"
name = "bench2"
path = "src/bench2.rs"

[[bin]]
edition = "2015"
name = "bin1"
path = "src/bin1.rs"

[[bin]]
edition = "2018"
name = "bin2"
path = "src/bin2.rs"

[[example]]
crate-type = ["staticlib"]
edition = "2015"
name = "example1"
path = "src/example1.rs"

[[example]]
edition = "2018"
name = "example2"
path = "src/example2.rs"

[[test]]
edition = "2015"
name = "test1"
path = "src/test1.rs"

[[test]]
edition = "2018"
name = "test2"
path = "src/test2.rs"

[build-dependencies.corge]
version = "6"

[dependencies]
foo = "1"

[dependencies.bar]
features = ["bar-feature", "bar-another-feature"]
version = "2"

[dependencies.baz]
features = ["baz-feature", "baz-feature2"]
version = "3"

[dev-dependencies]
qux = "4"

[dev-dependencies.zuul]
version = "5"

[features]
barfeature = ["foofeature"]
foofeature = []

[lib]
crate-type = ["lib", "rlib"]
edition = "2021"
name = "foo"
path = "src/lib.rs"

[package]
edition = "2021"
name = "some name"
resolver = "2"
version = "1.2.3"
workspace = "some/path/to/workspace"

[patch.crates-io]
[patch.crates-io.bar]
path = "my/local/bar"

[patch.crates-io.foo]
git = "https://github.com/example/foo"

[profile]
[profile.dev]
opt-level = 1
overflow-checks = false

[profile.release]
opt-level = 2
overflow-checks = true

[replace]
[replace."bar3:1.0.2"]
path = "my/local/bar3"

[replace."foo2:0.1.0"]
git = "https://github.com/example/foo2"

[some-unrecognized-object]
some-unrecognized-field = "some value"

[target]
[target."cfg(target_arch = \"x86\")".dependencies]
garply = "8"

[target."cfg(unix)".dependencies]
grault = "7"

[workspace]
resolver = "2"
default-members = ["path/to/member2", "path/to/member3/foo"]
exclude = ["crates/foo", "path/to/other"]
members = ["member1", "path/to/member2", "crates/*"]
